/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  theme: {
    extend: {
      colors: {
        'background':               '#0e0e0f',
        'surface':                  '#0e0e0f',
        'surface-dim':              '#0e0e0f',
        'surface-bright':           '#2c2c2d',
        'surface-container-lowest': '#000000',
        'surface-container-low':    '#131314',
        'surface-container':        '#1a191b',
        'surface-container-high':   '#201f21',
        'surface-container-highest':'#262627',
        'surface-variant':          '#262627',
        'surface-tint':             '#bd9dff',
        'inverse-surface':          '#fcf8f9',
        'on-background':            '#ffffff',
        'on-surface':               '#ffffff',
        'on-surface-variant':       '#adaaab',
        'inverse-on-surface':       '#565556',
        'outline':                  '#767576',
        'outline-variant':          '#484849',
        'primary':                  '#bd9dff',
        'primary-dim':              '#8a4cfc',
        'primary-fixed':            '#b28cff',
        'primary-fixed-dim':        '#a67aff',
        'primary-container':        '#b28cff',
        'on-primary':               '#3c0089',
        'on-primary-fixed':         '#000000',
        'on-primary-fixed-variant': '#390083',
        'on-primary-container':     '#2e006c',
        'inverse-primary':          '#742fe5',
        'secondary':                '#e4e1e6',
        'secondary-dim':            '#d6d3d7',
        'secondary-fixed':          '#e4e1e6',
        'secondary-fixed-dim':      '#d6d3d7',
        'secondary-container':      '#47464a',
        'on-secondary':             '#525155',
        'on-secondary-fixed':       '#3f3f42',
        'on-secondary-fixed-variant':'#5c5b5e',
        'on-secondary-container':   '#d2cfd3',
        'tertiary':                 '#ff97b2',
        'tertiary-dim':             '#f17799',
        'tertiary-fixed':           '#ff8eac',
        'tertiary-fixed-dim':       '#f77c9e',
        'tertiary-container':       '#fe81a4',
        'on-tertiary':              '#6a0a31',
        'on-tertiary-fixed':        '#380016',
        'on-tertiary-fixed-variant':'#711036',
        'on-tertiary-container':    '#5a0027',
        'error':                    '#ff6e84',
        'error-dim':                '#d73357',
        'error-container':          '#a70138',
        'on-error':                 '#490013',
        'on-error-container':       '#ffb2b9',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'Noto Sans KR', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        '4xl':   '2rem',
        '5xl':   '3rem',
        full:    '9999px',
      },
      keyframes: {
        fadeUp: {
          '0%':   { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        pulse2: {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '.5' },
        },
      },
      animation: {
        'fade-up':   'fadeUp 0.6s ease both',
        'fade-up-d': 'fadeUp 0.6s ease 0.2s both',
        shimmer:     'shimmer 2.5s linear infinite',
      },
      backgroundImage: {
        'hero-radial': 'radial-gradient(circle at 50% 50%, rgba(124,58,237,0.18) 0%, transparent 70%)',
      },
    },
  },
  plugins: [],
};
